AWSTemplateFormatVersion: 2010-09-09

Resources:
  usImmigrationData:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "us-immigration-data"
    DeletionPolicy: "Retain"
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties : 
      ClusterIdentifier : "redshift-cluster"
      ClusterType : "single-node"
      DBName : 'dev'
      IamRoles : 
        - Fn::GetAtt: [ UdacityRedshiftRole, Arn ]
      MasterUserPassword : "awsuser"
      MasterUsername : ""
      NodeType : "dc2.large"
      Port : 5439
      VpcSecurityGroupIds : 
        - "sg-0b2843c14d9e677a3"
  UdacityRedshiftRole:
    Type: AWS::IAM::Role
    Properties : 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "redshift.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "UdacityRedshiftPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "s3:Get*"
                  - "s3:List*"
                Resource: "*"
      RoleName : "UdacityRedshift"
